<a href="https://colab.research.google.com/github/Avichay3/Full-training/blob/main/Copy_of_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

Enjoy the puzzles!

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1 = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
np.size(array1)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array2 = np.zeros(10)
array2[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array3 = np.arange(10,50)

In [8]:
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
array4 = np.flip(array3)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
array5 = np.arange(0,9)
array5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
array6 = [1,2,0,0,4,0]
np.nonzero(array6)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
random_array = np.random.rand(3,3,3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr = np.random.randint(0,100, size=(10,10))
max_val = np.max(arr)
min_val = np.min(arr)
print(max_val)
print(min_val)
print(arr)


99
1
[[52 36 33 63 20 19 99 70 91 36]
 [31 40 22 85 50 17 92 15 87 41]
 [79 73 44 30 98  8 54 84 54 16]
 [73 49 72 95 89 92  3 58 30 39]
 [81 61 69 87 96 67 99 30 28 62]
 [75 79 12  8 58 99 18 37 86 49]
 [40 32 10 26 33 93 99 61 27 73]
 [44 92 87 79 81 54 21 96 54 35]
 [38 83  7  2 33 95 65 95 16 82]
 [79 22 50 68 66 96  1 14 71 88]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
array7 = np.random.randint(0,30, size=30)
array7.mean()

np.float64(14.133333333333333)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
array8 = np.ones((5,5))
array8[1:-1,1:-1] = 0
print(array8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
array8 = np.pad(array8, pad_width=1, constant_values=0)
array8

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
false
false
nan
true
false




#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
array9 = np.diag([1,2,3,4], k=-1)
array9

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
board = np.zeros((8,8))
board[1::2, ::2] = 1
board[::2, 1::2] = 1
board

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
arr = np.arange(6*7*8).reshape(6,7,8)
index = np.unravel_index(99, arr.shape)
print(index)

(np.int64(1), np.int64(5), np.int64(3))


:#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
pattern = np.array([[0, 1],
                    [1, 0]])
board = np.tile(pattern, (4, 4))
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
normali = np.random.random((5,5))
norm = (normali - normali.min()) / (normali.max() - normali.min())
print(norm)


[[0.50865568 0.25134966 0.63235342 0.52005581 0.2200381 ]
 [0.61106271 0.53757002 0.44535215 0.96022416 0.50848915]
 [0.54655101 0.99277539 0.44107886 0.84064605 0.00271654]
 [0.93968346 0.1720361  0.14129753 0.11167807 1.        ]
 [0.93953707 0.         0.21959706 0.70919918 0.17776036]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

1.   List item
2.   List item



In [25]:
A = np.random.random((5,3))
B = np.random.random((3,2))
np.dot(A,B)

array([[0.70097829, 0.95685043],
       [0.86109854, 1.28940412],
       [0.23165352, 0.33324161],
       [0.48660616, 0.95593725],
       [0.65155143, 1.12583848]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
negate = np.arange(11)
negate[(negate > 3) & (negate < 8)] *= -1
print(negate)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9,

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

legal,
legal,
legal,
legal,
legal,
ilegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Z = np.array([-1.2, -1.5, 1.2, 1.5])
Z_rounded = np.copysign(np.ceil(np.abs(Z)), Z)
print(Z_rounded)


[-2. -2.  2.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])

common = np.intersect1d(A, B)
print(common)

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [34]:
import warnings
warnings.filterwarnings('ignore')

warnings.filterwarnings('ignore', category=RuntimeWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2025-10-22 2025-10-23 2025-10-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [37]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [38]:
A = np.ones((3,3))
B = np.ones((3,3))

np.add(A, B, out=A)
np.divide(A, -2, out=A)
print(A)


[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [39]:
T = np.random.uniform(0,10,5)
print(T)

print(T - T % 1)
print(np.floor(Z))
print(np.trunc(Z))
print(np.int_(Z))

[1.69743808 8.35381057 4.1271719  5.99200484 3.5920263 ]
[1. 8. 4. 5. 3.]
[-2. -2.  1.  1.]
[-1. -1.  1.  1.]
[-1 -1  1  1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [42]:
Z = np.zeros((5,5)) + np.arange(5)
print(Z)
#another method
Z = np.tile(np.arange(5), (5,1))
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [43]:
from google.colab import auth
auth.authenticate_user()


In [45]:
!git config --global user.email "aviaimzina123456@gmail.com"
!git config --global user.name "Avichay3"

In [46]:
!git clone https://github.com/Avichay3/full_training.git


Cloning into 'full_training'...
fatal: could not read Username for 'https://github.com': No such device or address


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 63. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 64. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 65. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 66. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 67. How to swap two rows of an array? (★★★)

#### 68. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 69. How to compute averages using a sliding window over an array? (★★★)

#### 70. Compute a matrix rank (★★★)

#### 71. How to find the most frequent value in an array?

#### 72. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 73. How to get the n largest values of an array (★★★)

#### 74. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 75. Given a two dimensional array, how to extract unique rows? (★★★)