<a href="https://colab.research.google.com/github/Avichay3/Full-training/blob/numpy-pandas-training/Copy_of_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

Enjoy the puzzles!

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1 = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
np.size(array1)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array2 = np.zeros(10)
array2[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array3 = np.arange(10,50)

In [8]:
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
array4 = np.flip(array3)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
array5 = np.arange(0,9)
array5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
array6 = [1,2,0,0,4,0]
np.nonzero(array6)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
random_array = np.random.rand(3,3,3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr = np.random.randint(0,100, size=(10,10))
max_val = np.max(arr)
min_val = np.min(arr)
print(max_val)
print(min_val)
print(arr)


99
0
[[15 53  5 81 25 65 62 75 38 90]
 [88 81 71 60 34 85 17 64  8 37]
 [83 63 99 97  9 17 12 29 60  7]
 [29  3 43 25 89 89 29 81 75 47]
 [21 64 70 67 19 10 29 61 24 34]
 [82 21 55  9 70 48 46 32  8 19]
 [86 48 46 90 14 95 79 60 71  3]
 [41 83 88 86 62 82  6 63 51 49]
 [12 71  5 11 44 18  0 33 15 45]
 [51 99 24 22 63 76 58 58 52 70]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
array7 = np.random.randint(0,30, size=30)
array7.mean()

np.float64(15.266666666666667)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array8 = np.ones((5,5))
array8[1:-1,1:-1] = 0
print(array8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
array8 = np.pad(array8, pad_width=1, constant_values=0)
array8

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
false
false
nan
true
false




#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
array9 = np.diag([1,2,3,4], k=-1)
array9

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
board = np.zeros((8,8))
board[1::2, ::2] = 1
board[::2, 1::2] = 1
board

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
arr = np.arange(6*7*8).reshape(6,7,8)
index = np.unravel_index(99, arr.shape)
print(index)

(np.int64(1), np.int64(5), np.int64(3))


:#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
pattern = np.array([[0, 1],
                    [1, 0]])
board = np.tile(pattern, (4, 4))
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
normali = np.random.random((5,5))
norm = (normali - normali.min()) / (normali.max() - normali.min())
print(norm)


[[0.82760028 0.23164774 0.61090064 0.72836445 0.02774149]
 [0.84901274 0.0566217  0.28965307 0.68748169 0.        ]
 [0.59281269 0.39133432 0.3562845  0.99248192 0.17859147]
 [0.82875776 0.02462075 0.25790838 0.72202474 0.48777116]
 [0.57831631 0.94723747 1.         0.06058185 0.31172582]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [22]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

1.   List item
2.   List item



In [23]:
A = np.random.random((5,3))
B = np.random.random((3,2))
np.dot(A,B)

array([[0.04607692, 0.43912708],
       [0.12288376, 0.71981163],
       [0.29739634, 0.95185329],
       [0.35210586, 1.08259674],
       [0.2681567 , 0.89073869]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
negate = np.arange(11)
negate[(negate > 3) & (negate < 8)] *= -1
print(negate)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9,

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

legal,
legal,
legal,
legal,
legal,
ilegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [26]:
Z = np.array([-1.2, -1.5, 1.2, 1.5])
Z_rounded = np.copysign(np.ceil(np.abs(Z)), Z)
print(Z_rounded)


[-2. -2.  2.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [27]:
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])

common = np.intersect1d(A, B)
print(common)

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [28]:
import warnings
warnings.filterwarnings('ignore')

warnings.filterwarnings('ignore', category=RuntimeWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [29]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2025-11-03 2025-11-04 2025-11-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [30]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [31]:
A = np.ones((3,3))
B = np.ones((3,3))

np.add(A, B, out=A)
np.divide(A, -2, out=A)
print(A)


[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [32]:
T = np.random.uniform(0,10,5)
print(T)

print(T - T % 1)
print(np.floor(Z))
print(np.trunc(Z))
print(np.int_(Z))

[6.25952568 5.76361588 3.8396873  7.48368288 9.21999632]
[6. 5. 3. 7. 9.]
[-2. -2.  1.  1.]
[-1. -1.  1.  1.]
[-1 -1  1  1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [33]:
Z = np.zeros((5,5)) + np.arange(5)
print(Z)
#another method
Z = np.tile(np.arange(5), (5,1))
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [34]:
def gen():
    for i in range(10):
        yield i

Z = np.fromiter(gen(), dtype=int, count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [35]:
Z = np.linspace(0, 1, 12, endpoint=False)[1:-1]
print(Z)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [36]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.04167185 0.06452766 0.08636147 0.33814052 0.43026267 0.51911224
 0.58986977 0.71931788 0.78776147 0.97873909]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [37]:
Z = np.arange(10)
result = np.add.reduce(Z)
print(result)


45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [38]:
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)
print(np.array_equal(A, B))


False


#### 43. Make an array immutable (read-only) (★★☆)

In [39]:
Z = np.zeros(10)
Z.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [40]:
import numpy as np
coords = np.random.rand(10,2)
r = np.sqrt(coords[:, 0]**2 + coords[:, 1]**2)
theta = np.arctan2(coords[:, 1], coords[:, 0])

polar_coords = np.column_stack((r, theta))
print(polar_coords)

[[0.84100009 0.61829175]
 [0.68519234 0.27934785]
 [0.28775654 1.28429397]
 [1.01787512 0.87257379]
 [0.70637237 0.77858102]
 [1.06991519 0.44584693]
 [0.67966966 1.06242279]
 [0.74662266 0.26304545]
 [0.59245801 1.33944992]
 [0.77008066 0.98247951]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [41]:
v = np.random.rand(10)
v[v.argmax()] = 0
print(v)


[0.90449017 0.09707747 0.         0.49713152 0.11404464 0.31816434
 0.52998847 0.14585026 0.19788185 0.23817863]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [42]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)

X, Y = np.meshgrid(x, y)

structured = np.zeros(X.size, dtype=[('x', float), ('y', float)])
structured['x'] = X.ravel()
structured['y'] = Y.ravel()

print(structured)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [43]:
X = np.random.rand(5)
Y = np.random.rand(5)

C = 1 / (X[:, None] - Y[None, :])
print(C)


[[-13.10086721  -1.12977682 -38.7541129   -7.03265084  -3.07855452]
 [  1.58923065  -5.56903069   1.47110226   1.77502541   2.62647571]
 [  9.38494692  -1.42400214   6.36615346  24.57573389  -7.04506496]
 [ 11.27210081  -1.38872467   7.1817556   43.7607277   -6.258514  ]
 [-16.37157672  -1.14958224 -94.74757633  -7.87745579  -3.23019934]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [44]:
for dtype in [np.int8, np.int16, np.int32, np.int64, np.float32, np.float64]:
    info = np.iinfo(dtype) if np.issubdtype(dtype, np.integer) else np.finfo(dtype)
    print(f"{dtype}: min={info.min}, max={info.max}")


<class 'numpy.int8'>: min=-128, max=127
<class 'numpy.int16'>: min=-32768, max=32767
<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [45]:
np.set_printoptions(threshold=np.inf)
arr = np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [46]:
v = np.random.rand(10)
scalar = 0.5
closest_value = v[np.abs(v - scalar).argmin()]
print("Vector:", v)
print("Closest value to", scalar, "is", closest_value)

Vector: [0.4572037  0.17958953 0.88242438 0.18649003 0.35646508 0.03720643
 0.2083292  0.39443224 0.32746353 0.09725267]
Closest value to 0.5 is 0.4572037033108578


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [47]:
data = np.zeros(5, dtype=[('position', [('x', float), ('y', float)]),
                          ('color', [('r', float), ('g', float), ('b', float)])])

data['position']['x'] = np.random.rand(5)
data['position']['y'] = np.random.rand(5)
data['color']['r'] = np.random.rand(5)
data['color']['g'] = np.random.rand(5)
data['color']['b'] = np.random.rand(5)

print(data)


[((0.31858148, 0.93737478), (0.23256605, 0.62801613, 0.07098122))
 ((0.87814157, 0.76846006), (0.88352174, 0.8005486 , 0.91008375))
 ((0.87497493, 0.43944469), (0.65417351, 0.54984192, 0.12645855))
 ((0.43087566, 0.38012855), (0.7165665 , 0.37331233, 0.48824475))
 ((0.57150316, 0.07079984), (0.34344113, 0.34164501, 0.83410633))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [48]:
coords = np.random.rand(100, 2)

distances = np.sqrt(((coords[:, np.newaxis, :] - coords[np.newaxis, :, :]) ** 2).sum(axis=2))
print(distances)


[[0.         0.40036921 0.84230416 0.913233   0.81614032 0.52215643
  0.51743503 0.23943636 0.67459271 0.25449024 0.99681785 0.30546639
  0.71218236 0.43971728 0.52036196 0.82221533 0.74152306 0.75339351
  0.57768947 0.77384209 0.70869307 0.56992808 0.30868334 0.23041377
  0.32798826 0.26715159 0.42279578 0.83918323 0.7354548  0.18230954
  0.72550715 0.63541449 0.80508984 0.67704159 0.37411705 0.89665515
  0.36809631 0.73648045 0.18984921 0.33555558 0.21087387 0.40890012
  0.56784487 0.85763815 0.74160776 0.40513876 0.92305062 0.92830261
  0.49909707 0.53413596 0.68150026 0.2686159  0.72148894 0.17701582
  0.7093277  0.71263288 0.83986785 0.74000747 0.13547001 0.87792197
  0.56510716 0.93837955 0.83043015 0.9371512  0.56687859 0.40379651
  0.11105117 0.34136391 0.56951304 0.76379341 0.82137924 0.60280952
  0.34655223 0.31437007 0.27642704 0.27108823 0.84621067 0.33359716
  0.72301638 0.57640937 0.60953234 0.83171423 0.41824401 0.61589074
  0.65118751 0.93727844 0.87799163 0.45252372 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [49]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)
print(A.dtype)


[0 1 2 3 4 5 6 7 8 9]
int32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [50]:
arr = np.array([[10, 20], [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)


(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [51]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))

d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu)**2 / (2.0 * sigma**2)))

print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [52]:
n, m = 5, 5
p = 5
arr = np.zeros((n, m), dtype=int)
indices = np.random.choice(n * m, p, replace=False)
np.put(arr, indices, 1)
print(arr)


[[0 0 0 0 0]
 [0 1 0 0 1]
 [1 0 0 0 1]
 [0 0 0 0 0]
 [1 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [53]:
X = np.random.rand(3, 5)
X_centered = X - X.mean(axis=1, keepdims=True)

print(X_centered)

[[ 0.143609    0.22080152 -0.37531164  0.3598906  -0.34898948]
 [ 0.11556407  0.02836859  0.32297114 -0.46964446  0.00274066]
 [ 0.10509555 -0.25711399  0.05314146  0.0116228   0.08725418]]


#### 59. How to sort an array by the nth column? (★★☆)

In [54]:
arr = np.array([[1, 3, 5],
              [2, 2, 2],
              [3, 1, 4]])

n = 0
arr_sorted = arr[arr[:, n].argsort()]

print(arr_sorted)


[[1 3 5]
 [2 2 2]
 [3 1 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [55]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
null_col = np.all(arr == 0, axis=0)
print(null_col)


[False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [56]:
arr = np.linspace(0, 100, 20)
print(arr)
value = 76

nearest = arr[np.abs(arr - value).argmin()]
print(nearest)


[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
73.6842105263158


#### 62. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [57]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 0, 1, 2])
F = np.zeros(3)

np.add.at(F, I, X)

F


array([4., 6., 5.])

#### 63. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [58]:
w, h = 28, 28
image = np.random.randint(0, 256, (w, h, 3))

unique_colors = np.unique(image.reshape(-1, 3), axis=0)

print("number of unique colors:", len(unique_colors))


number of unique colors: 784


#### 64. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [59]:
A = np.random.rand(2, 3, 4, 5)
result = A.sum(axis=(-2, -1)) # sum the last two axis
print(result.shape)  # 2d array with the result


(2, 3)


#### 65. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [60]:
vec = np.array([1, 2, 3, 4, 5])
n_zeros = 3

new_len = len(vec) + (len(vec) - 1) * n_zeros
out = np.zeros(new_len, dtype=int)

out[::n_zeros + 1] = vec

print(out)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 66. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [61]:
image = np.arange(5*5*3).reshape(5,5,3)

weights = np.arange(25).reshape(5,5)

result = np.zeros_like(image)

for i in range(5):
    for j in range(5):
        result[i, j, :] = image[i, j, :] * weights[i, j]

print(result.shape)



(5, 5, 3)


#### 67. How to swap two rows of an array? (★★★)

In [62]:
A = np.arange(9).reshape(3, 3)
print("before:\n", A)

A[[0, 1]] = A[[1, 0]]
print("\n")
print("after:\n", A)


before:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


after:
 [[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 68. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [63]:
C = np.array([0, 2, 1, 0, 3])

A = np.repeat(np.arange(len(C)), C)

print("A =", A)
print("np.bincount(A) =", np.bincount(A))


A = [1 1 2 4 4 4]
np.bincount(A) = [0 2 1 0 3]


#### 69. How to compute averages using a sliding window over an array? (★★★)

In [64]:
x = np.arange(1, 10)
window_size = 3

window = np.ones(window_size) / window_size
moving_avg = np.convolve(x, window, mode='valid')

print(moving_avg)


[2. 3. 4. 5. 6. 7. 8.]


#### 70. Compute a matrix rank (★★★)

In [65]:
A = np.array([[10, 20, 10],
              [20, 40, 20],
              [5, 10, 5]])

rank = np.linalg.matrix_rank(A)
print(rank)


1


#### 71. How to find the most frequent value in an array?

In [66]:
arr = np.array([[1, 2, 3],
               [4, 2, 2],
               [6, 5 ,5]])
most_frequent = np.bincount(arr.ravel()).argmax()
print(most_frequent)

2


#### 72. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [67]:
Z = np.ones((16, 16))
block_size = 4


S = Z.reshape(4, block_size, 4, block_size).sum(axis=(1, 3))

print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 73. How to get the n largest values of an array (★★★)

In [68]:
Z = np.array([1, 3, 5, 7, 9, 2, 8, 4, 6])
n = 3

indices = np.argpartition(Z, -n)[-n:]
largest = Z[indices]

print("largest values:", largest)
print("sorted desceding:", np.sort(largest)[::-1])


largest values: [7 8 9]
sorted desceding: [9 8 7]


#### 74. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [69]:
Z = np.random.randint(0, 5, (10, 3))
print("matrix:\n", Z)

mask = np.any(Z != Z[:, [0]], axis=1)
result = Z[mask]

print("\nRows with unequal values:\n", result)


matrix:
 [[3 3 3]
 [3 3 3]
 [1 3 3]
 [2 2 1]
 [1 3 4]
 [3 2 2]
 [3 0 1]
 [3 2 1]
 [0 4 2]
 [2 1 4]]

Rows with unequal values:
 [[1 3 3]
 [2 2 1]
 [1 3 4]
 [3 2 2]
 [3 0 1]
 [3 2 1]
 [0 4 2]
 [2 1 4]]


#### 75. Given a two dimensional array, how to extract unique rows? (★★★)

In [70]:
Z = np.array([[1, 2, 3],
              [3, 2, 1],
              [1, 2, 3],
              [4, 5, 6]])

unique_rows = np.unique(Z, axis=0)

print(unique_rows)


[[1 2 3]
 [3 2 1]
 [4 5 6]]


In [71]:
print("finish")

finish
